#
# Copyright contributors to the Galasa project 
#
kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: main-simplatform-
  namespace: galasa-tekton
spec:
  params:
  pipelineRef:
    name: simplatform-repo-build
  podTemplate:
  workspaces:
  - name: git-workspace
    volumeClaimTemplate:
      spec:
        storageClassName: longhorn-temp
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
            