#
# Copyright contributors to the Galasa project 
#
apiVersion: v1
kind: Service
metadata:
  name: simbank-webservice-external
  namespace: galasa-prod
spec:
  type: NodePort
  ports:
  - name: webservice
    port: 2080
    protocol: TCP
    targetPort: 2080
  selector:
    app: simbank
