#
# Copyright contributors to the Galasa project 
#
apiVersion: v1
kind: Service
metadata:
  name: simbank-telnet-external
spec:
  type: NodePort
  ports:
  - name: telnet
    port: 2023
    protocol: TCP
    targetPort: 2023
  selector:
    app: simbank
