#
# Copyright contributors to the Galasa project 
#
apiVersion: v1
kind: Service
metadata:
  name: simbank-zosmf-external
spec:
  type: NodePort
  ports:
  - name: zosmf
    port: 2040
    protocol: TCP
    targetPort: 2040
  selector:
    app: simbank


