FROM ghcr.io/galasa-dev/openjdk:11-jdk

RUN mkdir /galasa

RUN useradd -u 1000 -d /galasa galasa              && \
    chown -R galasa:galasa /galasa

WORKDIR /galasa

USER galasa

COPY galasa-simplatform-application/galasa-simplatform-3270/target/galasa-simplatform-0.40.0.jar /galasa/simplatform.jar

VOLUME /galasa/.galasa
VOLUME /galasa/load

EXPOSE 2080/tcp
EXPOSE 2023/tcp
EXPOSE 2027/tcp
EXPOSE 2040/tcp