#
# Copyright contributors to the Galasa project 
#
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: simplatform-repo-build
spec:
  workspaces:
  - name: git-workspace
  params:
  - name: distBranch
    type: string
    default: {{ .Values.branch }}
  - name: refspec
    type: string
    default: +refs/heads/{{ .Values.branch }}:refs/heads/{{ .Values.branch }}
  - name: managersBranch
    type: string
    default: {{ .Values.managersBranch }}
  - name: noPush
    type: string
    default: ""
  tasks:
  - name: clone-simplatform
    taskRef: 
      name: git-clone
    params:
    - name: url
      value: https://github.com/galasa-dev/simplatform
    - name: revision
      value: $(params.distBranch)
    - name: refspec
      value: $(params.refspec)
    - name: depth
      value: "99999999"
    - name: subdirectory
      value: simplatform
    workspaces:
     - name: output
       workspace: git-workspace
  - name: simplatform
    taskRef:
      name: simplatform-repo-build
    runAfter:
    - clone-simplatform
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: managersSourceRepo
      value: http://galasadev-cicsk8s.hursley.ibm.com/$(params.managersBranch)/maven/managers/
    - name: noPush
      value: $(params.noPush)
    workspaces:
     - name: git-workspace
       workspace: git-workspace
  - name: recycle-simplatform
    taskRef:
      name: recycle-deployment
    runAfter:
    - simplatform
    when:
    - input: "$(params.noPush)"
      operator: notin
      values: ["--no-push"]
    params:
    - name: namespace
      value: galasa-branch-$(params.distBranch)
    - name: deployment
      value: maven-simplatform
